### ISSUE TITLE
Error while calling NVAPI Initialize

### ISSUE THREAD

**Issue by freitash** [pbaja/nvapi#1]
Hi, 

First of all, thank you for open sourcing this. AFAIK, it is the only wrapper in Python!

I cloned the repo, ran ` run.py`  in a terminal with admin privileges  and I got this error (complete traceback):

  ``` 
Traceback (most recent call last):
  File "C:\Users\Freitas\repos\nvapi\run.py", line 8, in <module>
    app = Application()
  File "C:\Users\Freitas\repos\nvapi\gui\__init__.py", line 20, in __init__
    self.api.init()
  File "C:\Users\Freitas\repos\nvapi\nvapi\nvapi.py", line 85, in init     
    self.native.Initialize()
  File "C:\Users\Freitas\repos\nvapi\nvapi\nvapi.py", line 70, in wrapper  
    result = native_function(*args, **kwargs)
OSError: exception: access violation writing 0xFFFFFFFFAA6B90D0
  ``` 
  
Using the latest NVDIA drivers as of this date.
Python version is `Python 3.9.4` 

I can't seem to find any results related with this issue or NVAPI specifically. 
Do you have any recommendations or potential fixes for this? 

Cheers!

**Comment by pbaja** [comment]
Just checked and I am getting the same error on Python 3.9.4
It works on Python 3.7.2 though, interesting.

I'll try to look into it this evening but i promise nothing :>

**Comment by pbaja** [comment]
Hey @freitash, can you check if it works for you now?

**Comment by freitash** [comment]
Hey @pbaja 

Still not working :/

**Steps**

1. `git pull`
2. `python example.py` (with and without admin privileges) 


**Stacktrace**

`Traceback (most recent call last):
  File "C:\Users\Freitas\repos\nvapi\example.py", line 4, in <module>
    api = NvidiaAPI()
  File "C:\Users\Freitas\repos\nvapi\nvapi\nvapi.py", line 107, in __init__
    self.initialize()
  File "C:\Users\Freitas\repos\nvapi\nvapi\nvapi.py", line 113, in initialize
    self.native.Initialize()
  File "C:\Users\Freitas\repos\nvapi\nvapi\nvapi.py", line 86, in wrapper
    result = native_function(*args, **kwargs)
OSError: exception: access violation writing 0x00007FF7EFCB97B0`

Let me know if I can help in any way!

Cheers
